"""Tests for the improvement API endpoint and persistence (Milestone 8)."""

from pathlib import Path

from fastapi.testclient import TestClient

from app.core import config
from app.main import app
from app.models.execution import ExecutionSummary, TestExecutionResult
from app.services import project_ingestion as ingestion

client = TestClient(app, raise_server_exceptions=False)

_FAILING_OUT = """\
/tests/test_app.py::test_add FAILED

============================= FAILURES =============================
________________________________ test_add ________________________________
/tests/test_app.py:12: in test_add
    raise NotImplementedError('Scaffold generated by AI Test Platform')
E   NotImplementedError: Scaffold generated by AI Test Platform
1 failed in 0.2s
"""


def _register_project(tmp_path: Path) -> str:
    src = tmp_path / "myproject"
    src.mkdir()
    (src / "app.py").write_text('def add(a, b):\n    return a + b\n', encoding="utf-8")
    (src / "test_app.py").write_text(
        'def test_add():\n    assert 1 + 1 == 2\n', encoding="utf-8")
    resp = client.post("/api/projects/from-path", json={"path": str(src)})
    assert resp.status_code == 200
    return resp.json()["project_id"]


def _run_pipeline(project_id: str) -> None:
    for step in ("profile", "discover", "plan", "generate"):
        resp = client.post(f"/api/projects/{project_id}/{step}")
        assert resp.status_code == 200


def _write_execution(project_id: str, stdout: str, status: str = "failed") -> None:
    exec_result = TestExecutionResult(
        project_id=project_id,
        overall_status=status,
        exit_code=1 if status == "failed" else 0,
        stdout=stdout,
        summary=ExecutionSummary(),
    )
    ingestion.save_execution(config.WORKSPACE_DIR, exec_result.model_dump_json())


def _generated_path(project_id: str) -> Path:
    return (
        Path(config.WORKSPACE_DIR) / project_id / "generated_tests" / "test_app.py"
    )


def _diagnose(project_id: str):
    resp = client.post(f"/api/projects/{project_id}/diagnose")
    assert resp.status_code == 200
    return resp.json()


class TestImproveEndpoint:
    def test_project_not_found_returns_404(self):
        resp = client.post("/api/projects/nonexistent/improve")
        assert resp.status_code == 404

    def test_no_diagnosis_returns_422(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        resp = client.post(f"/api/projects/{project_id}/improve")
        assert resp.status_code == 422
        assert "diagnose" in resp.json()["detail"].lower()

    def test_improve_scaffold(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        _write_execution(project_id, _FAILING_OUT)
        _diagnose(project_id)

        resp = client.post(f"/api/projects/{project_id}/improve")
        assert resp.status_code == 200
        data = resp.json()
        assert data["schema_version"] == 1
        assert data["status"] == "improved"
        assert data["files_modified"] == 1
        assert len(data["changes"]) == 1
        ch = data["changes"][0]
        assert ch["status"] == "improved"
        assert ch["test_function"] == "test_add"
        assert "from app import add" in ch["after"]

        # the generated test on disk is a real invocation, not a placeholder
        on_disk = _generated_path(project_id).read_text(encoding="utf-8")
        assert "Scaffold generated by AI Test Platform" not in on_disk
        assert "from app import add" in on_disk
        assert "add(None, None)" in on_disk  # values come from TestPlan edge evidence
        assert "assert callable(add)" not in on_disk  # no invented assertion
        assert "add(0, 0)" not in on_disk  # no fabricated 0-valued inputs
        assert "assert result == " not in on_disk  # no fabricated behavioral value

    def test_improve_persisted_and_returned_by_get(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        _write_execution(project_id, _FAILING_OUT)
        _diagnose(project_id)
        client.post(f"/api/projects/{project_id}/improve")

        get_resp = client.get(f"/api/projects/{project_id}")
        assert get_resp.status_code == 200
        improvement = get_resp.json()["improvement"]
        assert improvement is not None
        assert improvement["status"] == "improved"
        assert improvement["files_modified"] == 1

    def test_get_without_improvement_returns_null(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        resp = client.get(f"/api/projects/{project_id}")
        assert resp.status_code == 200
        assert resp.json()["improvement"] is None

    def test_improve_does_not_trigger_reexecution(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        _write_execution(project_id, _FAILING_OUT)
        diag_before = _diagnose(project_id)
        resp = client.post(f"/api/projects/{project_id}/improve")
        assert resp.status_code == 200
        # the persisted diagnosis is unchanged (no re-test/re-diagnose loop)
        raw_after = ingestion.read_diagnosis(config.WORKSPACE_DIR, project_id)
        from app.models.diagnosis import DiagnosisFinding, DiagnosisResult
        diag_after = DiagnosisResult.model_validate_json(raw_after)
        assert diag_after.findings == [DiagnosisFinding(**f) for f in diag_before["findings"]]


class TestImprovementPersistence:
    def test_save_and_read(self, tmp_path):
        ws = tmp_path / "workspace"
        pid = "proj-persist"
        (ws / pid / ".meta").mkdir(parents=True)
        payload = ('{"project_id": "' + pid + '", "schema_version": 1, '
                   '"created_at": "2021-01-01T00:00:00Z", "status": "no_change", '
                   '"files_modified": 0}')
        ingestion.save_improvement(ws, payload)
        assert (ws / pid / ".meta" / "improvement.json").is_file()
        data = ingestion.read_improvement(ws, pid)
        assert data is not None
        assert '"project_id"' in data

    def test_read_missing(self, tmp_path):
        ws = tmp_path / "workspace"
        assert ingestion.read_improvement(ws, "nonexistent") is None

    def test_malformed_read_returns_raw(self, tmp_path):
        ws = tmp_path / "workspace"
        pid = "malformed"
        (ws / pid / ".meta").mkdir(parents=True)
        (ws / pid / ".meta" / "improvement.json").write_text("{not json", encoding="utf-8")
        assert ingestion.read_improvement(ws, pid) == "{not json"
