"""Tests for the deterministic test-improvement core (Milestone 8)."""

from datetime import datetime, timezone
from pathlib import Path

from app.core import config
from app.models.codemap import (
    CodeMap,
    SourceClass,
    SourceFunction,
    SourceModule,
    TestMapping,
)
from app.models.diagnosis import (
    DiagnosisFinding,
    DiagnosisResult,
)
from app.models.test_plan import EdgeCase, TestPlan, TestPlanSummary, TestSpec
from app.services.improvement import improve_diagnosis

_CREATED = datetime.now(timezone.utc)


def _plan_for_add(target="add", file_path="app.py", args=("a", "b")):
    """TestPlan providing explicit edge-case evidence pinning every arg to None."""
    return TestPlan(
        project_id="p1", created_at=_CREATED,
        specs=[TestSpec(
            target_qualified_name=target, target_file=file_path, target_type="function",
            priority=1, test_type="unit", suggested_test_name=f"test_{target}",
            preconditions=[],
            edge_cases=[EdgeCase(parameter=a, case_type="none", description="None value")
                        for a in args],
            risk_score=0.5,
        )],
        summary=TestPlanSummary(total_specs=1, critical_count=1, high_count=0,
                                medium_count=0, low_count=0),
    )


def _finding(fid="f1", test_file="test_app.py", test_func="test_add",
             exc="NotImplementedError", category="exception"):
    return DiagnosisFinding(
        finding_id=fid,
        test_file=test_file,
        test_function=test_func,
        status="failed",
        failure_signature="sig",
        exception_type=exc,
        category=category,
    )


def _mk_codemap(**overrides):
    defaults = dict(
        project_id="p1",
        created_at=_CREATED,
        source_modules=[], test_functions=[], test_mappings=[], testable_targets=[],
        warnings=[],
    )
    defaults.update(overrides)
    return CodeMap(**defaults)


def _func_codemap(function_name="add", args=None, file_path="app.py", async_=False):
    fn = SourceFunction(
        name=function_name,
        qualified_name=function_name,
        file_path=file_path,
        line_start=1, line_end=3,
        args=args or ["a", "b"],
        is_async=async_,
    )
    mod = SourceModule(path=file_path, language="python", functions=[fn], classes=[])
    return _mk_codemap(source_modules=[mod], test_mappings=[
        TestMapping(
            test_function="test_add", test_file="test_app.py",
            source_target="add", source_file="app.py", confidence=0.9,
            method="import_analysis",
        )
    ])


def _diagnosis(findings):
    return DiagnosisResult(
        project_id="p1", created_at=_CREATED,
        overall_status="failures_diagnosed", findings=findings,
    )


def _placeholder_test_file():
    return (
        '"""Tests for app (auto-generated scaffold)."""\n'
        "\n"
        "def test_add():\n"
        '    """Test add.\n'
        '    """\n'
        '    raise NotImplementedError("Scaffold generated by AI Test Platform")\n'
        "\n"
        "def test_add_edge_a_none():\n"
        '    """Edge case: missing value."""\n'
        '    raise NotImplementedError("Edge case: missing value")\n'
        "\n"
    )


# ── Core improvement behavior ───────────────────────────────────────────

class TestImproveCore:
    def test_placeholder_function_improved(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")

        result = improve_diagnosis(
            _diagnosis([_finding()]), _func_codemap(), tmp_path, "p1",
            test_plan=_plan_for_add(),
        )
        assert result.status == "improved"
        assert result.files_modified == 1
        assert len(result.changes) == 1
        ch = result.changes[0]
        assert ch.status == "improved"
        assert ch.test_file == "test_app.py"
        assert "add" in ch.after
        assert "Scaffold generated by AI Test Platform" not in ch.after
        assert "assert result == " not in ch.after  # never fabricate a value

        # The improved file on disk reflects the change.
        on_disk = (gt / "test_app.py").read_text(encoding="utf-8")
        assert "def test_add():" in on_disk
        assert "from app import add" in on_disk
        assert "add(None, None)" in on_disk
        assert "add(0, 0)" not in on_disk  # no fabricated 0-valued inputs
        # sibling edge-case helper is untouched
        assert "test_add_edge_a_none" in on_disk
        assert "Edge case: missing value" in on_disk

    def test_parameter_names_alone_do_not_produce_values(self, tmp_path):
        # A function whose args have NO explicit TestPlan evidence must not be
        # filled with parameter-name-derived literals (e.g. add(0, 0)).
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        result = improve_diagnosis(
            _diagnosis([_finding()]), _func_codemap(), tmp_path, "p1",
            test_plan=None,
        )
        assert result.status == "blocked"
        assert result.changes[0].status == "blocked"
        assert "insufficient evidence to construct deterministic test inputs" in result.changes[0].reason
        on_disk = (gt / "test_app.py").read_text(encoding="utf-8")
        assert "Scaffold generated by AI Test Platform" in on_disk  # unchanged

    def test_deterministic_repeated_improvement(self, tmp_path):
        for ws in ("r1", "r2"):
            gt = tmp_path / ws / "p1" / "generated_tests"
            gt.mkdir(parents=True)
            (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        codemap = _func_codemap()
        plan = _plan_for_add()
        r1 = improve_diagnosis(_diagnosis([_finding()]), codemap, tmp_path / "r1", "p1", test_plan=plan)
        r2 = improve_diagnosis(_diagnosis([_finding()]), codemap, tmp_path / "r2", "p1", test_plan=plan)
        d1, d2 = r1.model_dump(), r2.model_dump()
        d1.pop("created_at", None)
        d2.pop("created_at", None)
        assert d1 == d2
        assert r1.status == "improved"

    def test_idempotent_repeat_on_same_workspace(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        codemap = _func_codemap()
        r1 = improve_diagnosis(_diagnosis([_finding()]), codemap, tmp_path, "p1", test_plan=_plan_for_add())
        assert r1.status == "improved"
        r2 = improve_diagnosis(_diagnosis([_finding()]), codemap, tmp_path, "p1", test_plan=_plan_for_add())
        # second pass has no remaining placeholder -> no_change, no file rewrite
        assert r2.status == "no_change"
        assert r2.files_modified == 0
        # the already-improved body is left intact
        on_disk = (gt / "test_app.py").read_text(encoding="utf-8")
        assert "Scaffold generated by AI Test Platform" not in on_disk

    def test_no_findings_is_no_change(self, tmp_path):
        result = improve_diagnosis(_diagnosis([]), _func_codemap(), tmp_path, "p1")
        assert result.status == "no_change"
        assert result.changes == []
        assert result.files_modified == 0

    def test_non_placeholder_category_blocked(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        result = improve_diagnosis(
            _diagnosis([_finding(category="assertion", exc="AssertionError")]),
            _func_codemap(), tmp_path, "p1",
        )
        assert result.status == "blocked"
        assert result.changes[0].status == "blocked"
        assert "NotImplementedError" in result.changes[0].reason

    def test_insufficient_evidence_unresolvable_target_blocked(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        # No source function for `add` -> cannot build a valid body.
        codemap = _mk_codemap(source_modules=[], test_mappings=[])
        result = improve_diagnosis(
            _diagnosis([_finding()]), codemap, tmp_path, "p1",
        )
        assert result.status == "blocked"
        assert result.changes[0].status == "blocked"
        assert "insufficient evidence" in result.changes[0].reason
        # No file was written / changed.
        on_disk = (gt / "test_app.py").read_text(encoding="utf-8")
        assert "Scaffold generated by AI Test Platform" in on_disk

    def test_method_target_blocked(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        cls = SourceClass(
            name="Calculator", qualified_name="Calculator", file_path="calc.py",
            line_start=1, line_end=10,
            methods=[SourceFunction(
                name="add", qualified_name="Calculator.add", file_path="calc.py",
                line_start=2, line_end=5, args=["self", "a", "b"],
            )],
        )
        mod = SourceModule(path="calc.py", language="python", classes=[cls])
        codemap = _mk_codemap(source_modules=[mod], test_mappings=[
            TestMapping(
                test_function="test_add", test_file="test_app.py",
                source_target="Calculator.add", source_file="calc.py",
                confidence=0.9, method="import_analysis",
            )
        ])
        result = improve_diagnosis(
            _diagnosis([_finding()]), codemap, tmp_path, "p1",
        )
        assert result.changes[0].status == "blocked"
        assert "top-level" in result.changes[0].reason

    def test_multi_finding_stable_ordering(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        content = (
            "def test_add():\n"
            '    raise NotImplementedError("Scaffold generated by AI Test Platform")\n'
            "\n"
            "def test_sub():\n"
            '    raise NotImplementedError("Scaffold generated by AI Test Platform")\n'
            "\n"
        )
        (gt / "test_calc.py").write_text(content, encoding="utf-8")

        fns = [
            SourceFunction(name="add", qualified_name="add", file_path="calc.py",
                           line_start=1, line_end=3, args=["a", "b"]),
            SourceFunction(name="sub", qualified_name="sub", file_path="calc.py",
                           line_start=4, line_end=6, args=["a", "b"]),
        ]
        mod = SourceModule(path="calc.py", language="python", functions=fns, classes=[])
        codemap = _mk_codemap(source_modules=[mod], test_mappings=[], testable_targets=[])
        plan = TestPlan(
            project_id="p1", created_at=_CREATED,
            specs=[
                TestSpec(
                    target_qualified_name=n, target_file="calc.py", target_type="function",
                    priority=1, test_type="unit", suggested_test_name=f"test_{n}",
                    preconditions=[],
                    edge_cases=[EdgeCase(parameter=a, case_type="none", description="None value")
                                for a in ("a", "b")],
                    risk_score=0.5,
                )
                for n in ("add", "sub")
            ],
            summary=TestPlanSummary(total_specs=2, critical_count=2, high_count=0,
                                    medium_count=0, low_count=0),
        )
        findings = [
            _finding(fid="f2", test_file="test_calc.py", test_func="test_sub"),
            _finding(fid="f1", test_file="test_calc.py", test_func="test_add"),
        ]
        result = improve_diagnosis(_diagnosis(findings), codemap, tmp_path, "p1", test_plan=plan)
        assert len(result.changes) == 2
        # findings order preserved in changes
        assert [c.test_function for c in result.changes] == ["test_sub", "test_add"]
        assert result.status == "improved"
        on_disk = (gt / "test_calc.py").read_text(encoding="utf-8")
        assert "from calc import add" in on_disk
        assert "from calc import sub" in on_disk


# ── Path & resource security ─────────────────────────────────────────────

class TestImproveSecurity:
    def test_traversal_path_blocked(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        f = _finding(test_file="../source/app.py")
        result = improve_diagnosis(_diagnosis([f]), _func_codemap(), tmp_path, "p1")
        assert result.changes[0].status == "blocked"
        assert "unsafe" in result.changes[0].reason
        # Nothing written outside generated_tests.
        assert not (tmp_path / "source" / "app.py").exists()

    def test_absolute_and_drive_and_non_py_blocked(self, tmp_path):
        for bad in ("C:\\source\\app.py", "/etc/passwd", "C:/x", "nested/../test.py"):
            f = _finding(test_file=bad)
            result = improve_diagnosis(_diagnosis([f]), _func_codemap(), tmp_path, "p1")
            assert result.changes[0].status == "blocked"
            met = result.changes[0].reason
            assert "unsafe" in met or result.changes[0].status == "blocked"

    def test_non_python_file_never_written(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        f = _finding(test_file="test_app.txt")
        result = improve_diagnosis(_diagnosis([f]), _func_codemap(), tmp_path, "p1")
        assert result.changes[0].status == "blocked"

    def test_source_and_meta_untouched(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        src = tmp_path / "p1" / "source"
        meta = tmp_path / "p1" / ".meta"
        gt.mkdir(parents=True)
        src.mkdir(parents=True)
        meta.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        (src / "app.py").write_text("def add(a, b):\n    return a + b\n", encoding="utf-8")
        (meta / "meta.json").write_text("{}", encoding="utf-8")
        improve_diagnosis(_diagnosis([_finding()]), _func_codemap(), tmp_path, "p1",
                          test_plan=_plan_for_add())
        assert "Scaffold generated by AI Test Platform" not in (gt / "test_app.py").read_text(encoding="utf-8")
        assert "def add(a, b):" in (src / "app.py").read_text(encoding="utf-8")
        assert (meta / "meta.json").read_text(encoding="utf-8") == "{}"

    def test_max_files_limit(self, tmp_path, monkeypatch):
        monkeypatch.setattr(config, "IMPROVE_MAX_TEST_FILES", 1)
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_a.py").write_text(_placeholder_test_file(), encoding="utf-8")
        (gt / "test_b.py").write_text(_placeholder_test_file(), encoding="utf-8")

        def finding(tf, fn):
            return _finding(fid=tf, test_file=tf, test_func=fn)

        fns = [
            SourceFunction(name="add", qualified_name="add", file_path="app.py",
                           line_start=1, line_end=3, args=["a", "b"]),
        ]
        mod = SourceModule(path="app.py", language="python", functions=fns, classes=[])
        codemap = _mk_codemap(source_modules=[mod], test_mappings=[], testable_targets=[])
        findings = [finding("test_a.py", "test_add"), finding("test_b.py", "test_add")]
        result = improve_diagnosis(_diagnosis(findings), codemap, tmp_path, "p1",
                                   test_plan=_plan_for_add())
        assert result.files_modified <= 1
        assert any("IMPROVE_MAX_TEST_FILES" in w for w in result.warnings)


# ── F1 evidence / F3 symlink / F4 fallback (audit remediation) ─────────

class TestAuditRemediation:
    def _func_codemap_for(self, fns, mappings=()):
        mod = SourceModule(path=fns[0].file_path, language="python",
                           functions=list(fns), classes=[])
        return _mk_codemap(source_modules=[mod], test_mappings=list(mappings))

    def test_explicit_edge_evidence_yields_deterministic_inputs(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        # boundary->Zero edge pins arg to 0
        plan = TestPlan(
            project_id="p1", created_at=_CREATED,
            specs=[TestSpec(
                target_qualified_name="add", target_file="app.py", target_type="function",
                priority=1, test_type="unit", suggested_test_name="test_add",
                preconditions=[],
                edge_cases=[
                    EdgeCase(parameter="a", case_type="boundary", description="Zero"),
                    EdgeCase(parameter="b", case_type="boundary", description="Zero"),
                ],
                risk_score=0.5,
            )],
            summary=TestPlanSummary(total_specs=1, critical_count=1, high_count=0,
                                    medium_count=0, low_count=0),
        )
        result = improve_diagnosis(_diagnosis([_finding()]), _func_codemap(), tmp_path, "p1",
                                   test_plan=plan)
        assert result.status == "improved"
        on_disk = (gt / "test_app.py").read_text(encoding="utf-8")
        assert "add(0, 0)" in on_disk

    def test_same_evidence_identical_output(self, tmp_path):
        for ws in ("x1", "x2"):
            gt = tmp_path / ws / "p1" / "generated_tests"
            gt.mkdir(parents=True)
            (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        codemap = _func_codemap()
        plan = _plan_for_add()
        a = improve_diagnosis(_diagnosis([_finding()]), codemap, tmp_path / "x1", "p1", test_plan=plan)
        b = improve_diagnosis(_diagnosis([_finding()]), codemap, tmp_path / "x2", "p1", test_plan=plan)
        assert a.changes[0].after == b.changes[0].after
        assert a.status == b.status == "improved"

    def test_no_invented_expected_return_or_assertion(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        result = improve_diagnosis(_diagnosis([_finding()]), _func_codemap(), tmp_path, "p1",
                                   test_plan=_plan_for_add())
        on_disk = (gt / "test_app.py").read_text(encoding="utf-8")
        assert "assert result == " not in on_disk
        assert "assert callable" not in on_disk  # no invented assertion
        assert "assert add(" not in on_disk
        assert "assert " + "add(" not in on_disk

    def test_placeholder_removed_when_evidence_sufficient(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        result = improve_diagnosis(_diagnosis([_finding()]), _func_codemap(), tmp_path, "p1",
                                   test_plan=_plan_for_add())
        assert result.status == "improved"
        on_disk = (gt / "test_app.py").read_text(encoding="utf-8")
        assert "Scaffold generated by AI Test Platform" not in on_disk

    def test_symlink_intermediate_dir_write_rejected(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        external = tmp_path / "external"
        external.mkdir()
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        link = gt / "subdir"
        try:
            link.symlink_to(external, target_is_directory=True)
        except (OSError, NotImplementedError):
            import pytest
            pytest.skip("symlink creation not permitted on this platform")
        # a finding targeting a file inside the symlinked subdir must be rejected
        f = _finding(test_file="subdir/test_app.py")
        result = improve_diagnosis(_diagnosis([f]), _func_codemap(), tmp_path, "p1",
                                   test_plan=_plan_for_add())
        assert result.changes[0].status == "blocked"
        # external dir untouched
        assert not (external / "test_app.py").exists()

    def test_containment_check_rejects_external_path(self, tmp_path):
        # Runs without symlink privileges: directly exercises the resolved-path
        # containment guard that defends the write path against directory
        # escapes (the symlink mechanism used by the test above).
        from app.services.improvement import _path_within
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        outside = tmp_path / "outside" / "test_app.py"
        outside.parent.mkdir()
        outside.write_text("x = 1\n")
        inside = gt / "test_app.py"
        inside.write_text("y = 2\n")
        assert _path_within(gt, inside) is True
        assert _path_within(gt, outside) is False
        # a nested real subdir stays contained
        nested = gt / "subdir" / "test_x.py"
        nested.parent.mkdir()
        assert _path_within(gt, nested) is True

    def test_unique_name_strip_fallback_allowed(self, tmp_path):
        gt = tmp_path / "p1" / "generated_tests"
        gt.mkdir(parents=True)
        (gt / "test_app.py").write_text(_placeholder_test_file(), encoding="utf-8")
        fn = SourceFunction(name="add", qualified_name="add", file_path="app.py",
                            line_start=1, line_end=3, args=["a", "b"])
        codemap = self._func_codemap_for([fn], mappings=[])  # no explicit mapping
        result = improve_diagnosis(_diagnosis([_finding()]), codemap, tmp_path, "p1",
                                   test_plan=_plan_for_add())
        # exact mapping absent, fallback to the unique `add` candidate
        assert result.status == "improved"

    def test_exact_mapping_preferred_over_fallback(self, tmp_path):
        # A name-strip would resolve `test_add` -> `add`, but an explicit CodeMap
        # test_mapping points to `addition`; the exact mapping must win.
        from app.services.improvement import _resolve_target, _source_index
        fn = SourceFunction(name="addition", qualified_name="addition", file_path="app.py",
                            line_start=1, line_end=3, args=["a", "b"])
        fn2 = SourceFunction(name="add", qualified_name="add", file_path="app.py",
                             line_start=1, line_end=3, args=["a", "b"])
        codemap = _mk_codemap(
            source_modules=[SourceModule(path="app.py", language="python",
                                         functions=[fn, fn2], classes=[])],
            test_mappings=[TestMapping(
                test_function="test_add", test_file="test_app.py",
                source_target="addition", source_file="app.py",
                confidence=0.9, method="import_analysis",
            )],
        )
        idx = _source_index(codemap)
        name, _ = _resolve_target("test_add", codemap, idx)
        assert name == "addition"

    def test_fallback_rejects_no_match(self, tmp_path):
        from app.services.improvement import _resolve_target, _source_index
        fn = SourceFunction(name="other", qualified_name="other", file_path="app.py",
                            line_start=1, line_end=3, args=["a", "b"])
        codemap = _mk_codemap(
            source_modules=[SourceModule(path="app.py", language="python",
                                         functions=[fn], classes=[])],
            test_mappings=[],
        )
        idx = _source_index(codemap)
        name, fn_res = _resolve_target("test_add", codemap, idx)
        assert name is None and fn_res is None

    def test_fallback_rejects_ambiguous_same_name_across_modules(self, tmp_path):
        """F4-1: two top-level `add` functions in distinct modules with no
        explicit mapping must be REJECTED, never silently selecting a module."""
        from app.services.improvement import _resolve_target, _source_index
        fn_a = SourceFunction(name="add", qualified_name="pkg_a.add",
                              file_path="pkg_a/__init__.py", line_start=1, line_end=3,
                              args=["a", "b"])
        fn_b = SourceFunction(name="add", qualified_name="pkg_b.add",
                              file_path="pkg_b/__init__.py", line_start=1, line_end=3,
                              args=["a", "b"])
        codemap = _mk_codemap(
            source_modules=[
                SourceModule(path="pkg_a/__init__.py", language="python",
                             functions=[fn_a], classes=[]),
                SourceModule(path="pkg_b/__init__.py", language="python",
                             functions=[fn_b], classes=[]),
            ],
            test_mappings=[],
        )
        idx = _source_index(codemap)
        name, fn_res = _resolve_target("test_add", codemap, idx)
        # neither module may be selected
        assert name is None and fn_res is None

    def test_fallback_single_unique_still_resolves(self, tmp_path):
        """A single unique `add` in one module still resolves via fallback."""
        from app.services.improvement import _resolve_target, _source_index
        fn = SourceFunction(name="add", qualified_name="pkg.add",
                            file_path="pkg/__init__.py", line_start=1, line_end=3,
                            args=["a", "b"])
        codemap = _mk_codemap(
            source_modules=[SourceModule(path="pkg/__init__.py", language="python",
                                         functions=[fn], classes=[])],
            test_mappings=[],
        )
        name, fn_res = _resolve_target("test_add", codemap, _source_index(codemap))
        assert name == "pkg.add"
        assert fn_res is fn

    def test_explicit_mapping_selects_correct_module_amid_ambiguity(self, tmp_path):
        """An explicit pkg_a.add mapping resolves pkg_a.add even when a same-name
        pkg_b.add exists — exact qualified mapping still preferred."""
        from app.services.improvement import _resolve_target, _source_index
        fn_a = SourceFunction(name="add", qualified_name="pkg_a.add",
                              file_path="pkg_a/__init__.py", line_start=1, line_end=3,
                              args=["a", "b"])
        fn_b = SourceFunction(name="add", qualified_name="pkg_b.add",
                              file_path="pkg_b/__init__.py", line_start=1, line_end=3,
                              args=["a", "b"])
        codemap = _mk_codemap(
            source_modules=[
                SourceModule(path="pkg_a/__init__.py", language="python",
                             functions=[fn_a], classes=[]),
                SourceModule(path="pkg_b/__init__.py", language="python",
                             functions=[fn_b], classes=[]),
            ],
            test_mappings=[TestMapping(
                test_function="test_add", test_file="test_app.py",
                source_target="pkg_a.add", source_file="pkg_a/__init__.py",
                confidence=0.9, method="import_analysis",
            )],
        )
        idx = _source_index(codemap)
        name, fn_res = _resolve_target("test_add", codemap, idx)
        assert name == "pkg_a.add"
        assert fn_res is fn_a
