"""Tests for the diagnosis API endpoint (Milestone 7)."""

from pathlib import Path

from fastapi.testclient import TestClient

from app.core import config
from app.main import app
from app.models.execution import ExecutionSummary, TestExecutionResult
from app.services import project_ingestion as ingestion

client = TestClient(app, raise_server_exceptions=False)

_FAILING_OUT = """\
/tests/test_app.py::test_add FAILED

============================= FAILURES =============================
________________________________ test_add ________________________________
/tests/test_app.py:12: in test_add
    raise NotImplementedError('Scaffold generated by AI Test Platform')
E   NotImplementedError: Scaffold generated by AI Test Platform
1 failed in 0.2s
"""


def _register_project(tmp_path: Path) -> str:
    src = tmp_path / "myproject"
    src.mkdir()
    (src / "app.py").write_text('def add(a, b):\n    return a + b\n', encoding="utf-8")
    (src / "test_app.py").write_text(
        'def test_add():\n    assert 1 + 1 == 2\n', encoding="utf-8")
    resp = client.post("/api/projects/from-path", json={"path": str(src)})
    assert resp.status_code == 200
    return resp.json()["project_id"]


def _run_pipeline(project_id: str) -> None:
    for step in ("profile", "discover", "plan", "generate"):
        resp = client.post(f"/api/projects/{project_id}/{step}")
        assert resp.status_code == 200


def _write_execution(project_id: str, stdout: str, status: str = "failed") -> TestExecutionResult:
    exec_result = TestExecutionResult(
        project_id=project_id,
        overall_status=status,
        exit_code=1 if status == "failed" else 0,
        stdout=stdout,
        summary=ExecutionSummary(),
    )
    ingestion.save_execution(config.WORKSPACE_DIR, exec_result.model_dump_json())
    return exec_result


class TestDiagnoseEndpoint:
    def test_project_not_found_returns_404(self):
        resp = client.post("/api/projects/nonexistent/diagnose")
        assert resp.status_code == 404

    def test_no_execution_returns_422(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        resp = client.post(f"/api/projects/{project_id}/diagnose")
        assert resp.status_code == 422
        assert "execute" in resp.json()["detail"].lower()

    def test_no_failures(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        _write_execution(
            project_id,
            "/tests/test_app.py::test_add PASSED\n",
            status="passed",
        )
        resp = client.post(f"/api/projects/{project_id}/diagnose")
        assert resp.status_code == 200
        data = resp.json()
        assert data["overall_status"] == "no_failures"
        assert data["findings"] == []
        assert data["schema_version"] == 1

    def test_failure_diagnosis(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        _write_execution(project_id, _FAILING_OUT)
        resp = client.post(f"/api/projects/{project_id}/diagnose")
        assert resp.status_code == 200
        data = resp.json()
        assert data["overall_status"] == "failures_diagnosed"
        assert len(data["findings"]) >= 1
        f = data["findings"][0]
        assert f["category"] == "exception"
        assert f["exception_type"] == "NotImplementedError"
        assert f["failure_signature"]

    def test_persisted_and_returned_by_get(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        _write_execution(project_id, _FAILING_OUT)
        resp = client.post(f"/api/projects/{project_id}/diagnose")
        assert resp.status_code == 200

        get_resp = client.get(f"/api/projects/{project_id}")
        assert get_resp.status_code == 200
        assert get_resp.json()["diagnosis"] is not None
        assert get_resp.json()["diagnosis"]["overall_status"] == "failures_diagnosed"

    def test_get_without_diagnosis_returns_null(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        resp = client.get(f"/api/projects/{project_id}")
        assert resp.status_code == 200
        assert resp.json()["diagnosis"] is None

    def test_deterministic_repeated_diagnosis(self, tmp_path):
        project_id = _register_project(tmp_path)
        _run_pipeline(project_id)
        _write_execution(project_id, _FAILING_OUT)
        client.post(f"/api/projects/{project_id}/diagnose")
        client.post(f"/api/projects/{project_id}/diagnose")
        # Repeated diagnosis remains stable for the same inputs.
        resp = client.get(f"/api/projects/{project_id}")
        data = resp.json()["diagnosis"]
        assert len(data["findings"]) >= 1
        assert data["findings"][0]["category"] == "exception"


class TestDiagnosisPersistence:
    def test_save_and_read(self, tmp_path):
        ws = tmp_path / "workspace"
        pid = "proj-persist"
        (ws / pid / ".meta").mkdir(parents=True)
        payload = '{"project_id": "' + pid + '", "overall_status": "no_failures", "findings": []}'
        ingestion.save_diagnosis(ws, payload)
        assert (ws / pid / ".meta" / "diagnosis.json").is_file()
        data = ingestion.read_diagnosis(ws, pid)
        assert data is not None
        assert '"project_id"' in data

    def test_read_missing(self, tmp_path):
        ws = tmp_path / "workspace"
        assert ingestion.read_diagnosis(ws, "nonexistent") is None

    def test_malformed_read_returns_raw(self, tmp_path):
        ws = tmp_path / "workspace"
        pid = "malformed"
        (ws / pid / ".meta").mkdir(parents=True)
        (ws / pid / ".meta" / "diagnosis.json").write_text("{not json", encoding="utf-8")
        # read_diagnosis returns the raw text; validation happens at the model layer.
        assert ingestion.read_diagnosis(ws, pid) == "{not json"
